### ISSUE TITLE
Cannot fullscreen video in external iframe on iOS

### ISSUE THREAD

**Issue by firewaller** [bdougherty/BigScreen#19]
My Vimeo embeds work with BigScreen on my desktop, but not on iOS.

It looks like it fails during `BigScreen.videoEnabled($('iframe)[0])`. Is there a way to bypass this?

FYI: [Vimeo support states](https://vimeo.com/forums/api/topic:277283#comment_13810195) that their API does not integrate with native JS fullscreen.

**Comment by bdougherty** [comment]
BigScreen needs to be able to have access to the `<video>` on iOS, which is not possible to do with an `<iframe>` from a different origin.
