### ISSUE TITLE
Not working on nested iframe

### ISSUE THREAD

**Issue by uc-uga** [bdougherty/BigScreen#25]
Hello,

This plugin was working inside iframe but when 2 level of iframe nesting applying on it reruns false on BigScreen.enabled.

Any solution ?

**Comment by bdougherty** [comment]
Do all the iframes have the `allowfullscreen` attribute?

**Comment by uc-uga** [comment]
Thanks for help. i have added allowfullscreen in all iframe & now its working fine.
