### ISSUE TITLE
Demo does not work on Chrome 60+ on Android

### ISSUE THREAD

**Issue by DanielRuf** [bdougherty/BigScreen#28]
Nothing happens when I click the fullscreen button in the demo.

**Comment by datermine** [comment]
I'm experiencing this same bug. 

Failed to execute 'requestFullscreen'...

Any workarounds?

**Comment by DanielRuf** [comment]
I guess this project is not actively maintained anymore as it seems.

**Comment by datermine** [comment]
FYI - I just tried out: https://github.com/sindresorhus/screenfull.js

Works pretty well.

**Comment by bdougherty** [comment]
Unfortunately, I don't have much time to work on this library anymore.

The primary benefit of BigScreen over other libraries is for video (especially embedded in an `<iframe>`), so if you're not using it for that, screenfull is a good option.

**Comment by LiamKarlMitchell** [comment]
Relevant error I think.

Tried with Google Chrome and Canary.
Version 72.0.3626.109 (Official Build) (64-bit)
Version 74.0.3718.0 (Official Build) canary (32-bit)

Still works in Edge and FireFox.

```
bigscreen.js:2 Uncaught (in promise) TypeError: Failed to execute 'requestFullscreen' on 'Element': parameter 1 ('options') is not an object.
    at Object.request (bigscreen.js:2)
    at HTMLInputElement.requestFullScreen (3DVoCommonJs.min.js?version=3.6.2:1)
```
